apiVersion: v1
kind: Pod
metadata:
  name: debian1
  labels:
    app: debian1
spec:
  containers:
  - image: debian:buster
    command:
      - sleep
      - "360000"
    imagePullPolicy: IfNotPresent
    name: debian1
  restartPolicy: Always
